CREATE SCHEMA HR;

CREATE SEQUENCE HR.VIT_RSA_GENERIC_SEQ
    START WITH 50002
    INCREMENT 1;

CREATE TABLE HR.DEMO_ACCOUNT_TYPE(
    ACCOUNT_TYPE_ID BIGINT NOT NULL,
    MNEMONIC VARCHAR(100) NOT NULL UNIQUE,
    ACCOUNT_TYPE_NAME   VARCHAR(255) NOT NULL,
    CREATION_DATE DATE NOT NULL,
    PRIMARY KEY(ACCOUNT_TYPE_ID)
);

CREATE TABLE HR.DEMO_ACCOUNT_TX(
    TX_ID BIGINT NOT NULL,
    ACCOUNT_TYPE_ID BIGINT NOT NULL,
    MEMBER_ID BIGINT NOT NULL,
    AMOUNT BIGINT NOT NULL,
    TX_DATE DATE NOT NULL,
    PRIMARY KEY(TX_ID),
    CONSTRAINT FK_ACCOUNT_TYPE_ID FOREIGN KEY (ACCOUNT_TYPE_ID) REFERENCES HR.DEMO_ACCOUNT_TYPE(ACCOUNT_TYPE_ID)
);